### ISSUE TITLE
(Android) Images not showing up in Offer Profile pages

### ISSUE THREAD

**Issue by tallmadge** [SmallShopsUnited/React-Native-Mobile-App#41]
![screenshot_20180930-180522](https://user-images.githubusercontent.com/13523241/46263974-586a2280-c4dc-11e8-9c69-20a0b0122ab3.png)

**Comment by Stacyadam** [comment]
Okay. I have some new solutions for the image issues we have been having. If an image errors now it is getting caught and handled instead of potentially crashing the app. I also put a custom exception handler at the top level that will catch a native error and send an email with the error information so we can actually see what these errors are. I'll have a build for both platforms later tonight.

**Comment by tallmadge** [comment]
I look forward to it.  In the meantime, I've compressed every image in the 2019 Gift Packs.  Now I'll do the same for the 2018 Packs.

**Comment by tallmadge** [comment]
I believe we've got this fixed, so I'm closing the issue.  We'll reopen if we notice the problem again.
